### ISSUE TITLE
[App] Criar diagramas de sequência

### ISSUE THREAD

**Issue by GuilhermeRoque** [best-software-company/app#2]
- [x] Registro
- [x] Login
- [x] Visualizar Perfil
- [x] Alterar Perfil
- [x] Configurar Tarefa
- [x] Editar Tarefa
- [x] Finalizar Tarefa
- [x] Pontuar Tarefa
- [x] Configurar Rotina
- [x] Visualizar Rotina
- [x] Configurar Grupo
- [x] Visualizar Grupo
- [x] Pesquisar Usuário

**Comment by fpcardoso** [comment]
Após revisão dos casos de uso, foram criados os diagramas de sequência. Os mesmos estão no arquivo [Diagramas de Sequência](https://github.com/best-software-company/docs/blob/master/markdown/Diagrama-de-sequencia.md).
