### ISSUE TITLE
[App] Levantamento das regras de negócios

### ISSUE THREAD

**Issue by GuilhermeRoque** [best-software-company/app#3]
Criar o documento **Regras.md** no repositório _docs_ com regras de negócio do app.

**Comment by fpcardoso** [comment]
As regras de negócios estão descritas no arquivo [Levantamento de Requisitos](https://github.com/best-software-company/docs/blob/mod-requisitos/Levantamento-de-Requisitos.md) no repositório docs.

**Comment by luizaalves** [comment]
[Levantamento de Requisitos](https://github.com/best-software-company/docs/blob/master/Levantamento-de-Requisitos.md)
