### ISSUE TITLE
[App] Levantamento de requisitos

### ISSUE THREAD

**Issue by GuilhermeRoque** [best-software-company/app#4]
Criar o documento **Requisitos.md** no repositório _docs_ com requisitos funcionais e não funcionais.

**Comment by fpcardoso** [comment]
Inseri alguns requisitos e coloquei uma identificação para os mesmos.
Fiz essas alterações na branch [mod-requisitos](https://github.com/best-software-company/docs/blob/mod-requisitos/Levantamento-de-Requisitos.md) para que vocês possam avaliar antes de fazer o merge pro master.

**Comment by luizaalves** [comment]
[Levantamento de requisitos](https://github.com/best-software-company/docs/blob/master/Levantamento-de-Requisitos.md)

**Comment by GuilhermeRoque** [comment]
Foi criado o arquivo [Levantamento-de-Requisitos.md](https://github.com/best-software-company/docs/blob/master/Levantamento-de-Requisitos.md) no repositório docs.
