### ISSUE TITLE
[App] Criar diagrama de casos de uso

### ISSUE THREAD

**Issue by GuilhermeRoque** [best-software-company/app#5]
Diagrama de casos de uso **Casos_HT** está sendo compartilhado com os membros do time pelo Google Drive. Arquivo final estará no respositório _docs_.

**Comment by fpcardoso** [comment]
Inseri o aquivo [Análise de Requisitos](https://github.com/best-software-company/docs/blob/mod-requisitos/Analise-de-Requisitos.md) no branch mod-requisitos com descrição de alguns casos de uso.
Peço a revisão dos demais membros antes de realizar merge para o branch master.

**Comment by luizaalves** [comment]
[Casos de uso]( https://github.com/best-software-company/docs/blob/master/Analise-de-Requisitos.md)

**Comment by GuilhermeRoque** [comment]
Foi criado a pasta images no repositório docs com o arquivo de imagem [use_case_diagram.png](https://github.com/best-software-company/docs/blob/master/images/use_cases_diagram.png)  e a pasta diagrams com o arquivo [use_cases.asta](https://github.com/best-software-company/docs/blob/master/diagrams/use_cases.asta) que foi utilizado para desenvolvimento.
