### ISSUE TITLE
[App] Ambientação Android Studio

### ISSUE THREAD

**Issue by GuilhermeRoque** [best-software-company/app#6]
DoD: IDE instalada, desenvolvimento Android estudado (básico)

**Comment by luizaalves** [comment]
O que será entregue: listar as funcionalidades, ferramentas e automatizações que a aplicação pode oferecer.

**Comment by luizaalves** [comment]
[Ambientação-inicial](https://github.com/best-software-company/docs/blob/master/Ambientacao-android-studio.md)

**Comment by GuilhermeRoque** [comment]
Foi criado o arquivo [Ambientacao-android-studio.md](https://github.com/best-software-company/docs/blob/master/Ambientacao-android-studio.md) no repositório docs.
